
server:
  port: ${PORT}

spring:
  application:
    name: member

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_HOST}:8761/eureka

sns:
  kakao:
    id: ${KAKAO_CLIENT_ID}
    url: ${KAKAO_REDIRECT_URL}
  google:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_SECRET_KEY}
    url: ${GOOGLE_REDIRECT_URL}
  apple:
    id: ${APPLE_CLIENT_ID}
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    private-key: ${APPLE_PRIVATE_KEY}
    url: ${APPLE_REDIRECT_URL}